### ISSUE TITLE
Create slide button doesn't work

### ISSUE THREAD

**Issue by Bubcool1** [benemmons/txtPresentation#4]
If you try to create a slide you are unable to make one, to reproduce this you may need to delete all slides and then try to make a new one. This would then reproduce this.
![image](https://user-images.githubusercontent.com/32127787/46405205-63e96380-c6ff-11e8-809c-05af2f644250.png)

**Comment by benemmons** [comment]
[Duplicate Issue](https://github.com/benemmons/txtPresentation/issues/1)
